### ISSUE TITLE
Check out zenodo-client

### ISSUE THREAD

**Issue by cthoyt** [wikipathways/pyzenodo4wpdata#1]
Might be worth checking out https://GitHub.com/cthoyt/zenodo-client. I implemented a lot of the functionality for dealing with versions and interacting with zenodo’s api in python in a (hopefully) reusable way.

**Comment by cthoyt** [comment]
On the other hand it’s also nice to have a self-contained system.

**Comment by AlexanderPico** [comment]
Looks super helpful... if I hadn't already implemented a direct API solution :) Thanks for sharing for others to check out and for future reference.
